name: "service-singleimage"
on:
  workflow_dispatch:
    inputs:
      aws_env:
        type: choice
        description: Action the QA or PROD server
        options:
          - qa
          - prod
      action:
        type: choice
        description: Use this menu to deploy, re-deploy or shut down the service
        options:
          - deploy
          - destroy
          - upgrade
      version:
        type: choice
        description: Docker hub tag for the version you want to deploy
        options:
          # curl 'https://registry.hub.docker.com/v2/repositories/budibase/budibase/tags?page_size=1024' | jq '."results"[]["name"]' | tr -d '"' | awk '{print "- "$1}'
          - latest
          - v2.8.14
          - v2.8.10
          - v2.7.36
          - v2.7.30
          - v2.7.26
          - v2.7.17
          - v2.7.14
          - v2.7.7
          - v2.6.11
          - v2.6.1
          - v2.5.9
          - v2.4.44
          - v2.4.30
          - v2.4.4
          - v2.4.3
          - v2.4.2
          - v2.3.21
          - v2.3.19
          - v2.3.0
          - v2.2.23
          - v2.2.9
          - v2.2.3
          - v2.2.1
          - v2.1.42
          - v2.1.41
          - v2.1.39
          - v2.1.28
          - v2.1.27
          - v2.1.26
          - v2.1.24
          - v2.1.23
          - v2.1.21
          - v2.1.15
          - v2.1.14
          - v2.1.13
          - v2.1.11
          - v2.1.9
          - v2.1.1
          - v2.0.37
          - v2.0.31
          - v2.0.30
          - v2.0.26
          - v2.0.25
          - v2.0.24
          - v2.0.23
          - v2.0.21
          - v2.0.12
          - v2.0.9
          - v2.0.6
          - v2.0.3
          - v1.4.17
          - v1.4.7
          - v1.3.18
          - v1.3.15
          - v1.3.14
          - v1.3.11
          - v1.2.52
          - v1.2.50
          - v1.2.9
          - v1.2.2
          - v1.1.28

jobs:
  deploy-something:
    name: "singleimage-tf-apply-qa"
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.action == 'deploy') && (github.event.inputs.aws_env == 'qa') }}
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Summary
        id: summary
        run: echo "Deployed version ${{ github.event.inputs.version }} to sub.domain.com"
